### ISSUE TITLE
Auto-Close Option breaks flyout buttons

### ISSUE THREAD

**Issue by negue** [ScottIngram/UFO#9] opened 2024-01-17 21:34 UTC
I don't know for how many versions it is but currently for me the Auto-Close just closes the Flyout

![image](https://github.com/ScottIngram/UFO/assets/842273/97b569e5-8360-49e5-b761-49c95e19cf24)

Trying to trigger Dreamwalking (dunno if thats the correct name in english, the teleport for druids)

![image](https://github.com/ScottIngram/UFO/assets/842273/c2a24f47-a1bc-4edd-beb9-2435140b89f4)

**Comment by ScottIngram** [comment] 2024-01-18 03:44
Yes, the 'Auto-Close UFO' just closes the flyout.  I use the term "UFO" to mean "flyout" and vice versa.  Sorry, I should translate the configuration screen.  What's your preferred language?

Are you reporting that you can't cast Dreamwalking from a UFO?

**Comment by ScottIngram** [comment] 2024-01-19 19:08
> none of the buttons trigger anything when "Auto Close UFO" is active

THANK YOU!  A few other users have reported the buttons don't work but you're the first to figure out it's the auto-close that's causing the problem.  Excellent, this gives me the clue I needed!

**Comment by ScottIngram** [comment] 2024-01-19 21:28
@negue may I ask for a little more info to help me recreate this problem please?  Can you tell me:
* a list of what other addons you're using
* does this happen when the UFO is on any particular action bar? Or does it happen on every bar?

I've been experimenting with various Bliz UI settings and random addons, but I'm failing to recreate this bug :-(

**Comment by ScottIngram** [comment] 2024-01-20 19:22
@negue , ok, I've made a guess as to what is causing the problem.  If you can, please test it for me?
* click the "9-auto-close-option-breaks-flyout-buttons" link in the right column near the top of this page
* on the next page click the "<> Code" menu and select "Download Zip"
* copy the contents of that zip into your wow/_retail_/interface/addons dir and replace the existing UFO dir.

**Comment by negue** [comment] 2024-01-21 03:33
Sadly that didn't fix it.

I reloaded it once and also restarted Wow just to be sure.

I disabled all addons but UFO. Tried it on every action bar there is, tried it with a new UFO Group using only the hearthstone still nothing triggers for me. 

I'm playing on a German Wow Client, maybe there is something that uses some english only variable? 

Other idea, what if the auto close just triggers 2-3 seconds later? Just speculating here, havent read any of the Code yet (also missing a lot of LUA and WoW Addon Knowhow as well haha)

**Comment by negue** [comment] 2024-01-21 03:35
Just had another idea, recently GSE "broke" for me and I think it was because I had this option enable "left click handled as right click" or how its called in english there I had to change the GSE macro to use a different mousebutton instead

Could this be also the issue here?

**Comment by ScottIngram** [comment] 2024-01-23 00:12
> Sadly that didn't fix it.
Well darn!

> I disabled all addons but UFO [and a lot more]
Thanks so much for the time effort!

> what if the auto close just triggers 2-3 seconds later
That was my first thought too, but, unless there is some very clever trick that I can't think of, then, Blizzard's secure/restricted environment doesn't provide a delayed function call or even any knowledge of the passage of time.

I'll keep trying.

**Comment by ScottIngram** [comment] 2024-01-27 08:14
@negue 
Another stab i the dark... maybe this line will do the trick?

file: ui/FlyoutMenu.lua
line #100
`        SecureHandlerWrapScript(button, "PostClick", button, "return self, 'foo'", CLOSE_ON_CLICK_SCRIPTLET)
`

**Comment by negue** [comment] 2024-01-27 16:09
Changed the line / reloaded still not reacting on a click

Also just to be sure changed the client to english but also nothing happens

Even tried the oldest version (the oldest release on github) not working.

Maybe we need a debug mode that just spams various console outputs, what if the PostClick event itself not called? (Just throwing in ideas in here :D, no know how yet how WoW Addon System works xD)

**Comment by ScottIngram** [comment] 2024-01-28 05:27
> still not reacting on a click
Sad Panda!

You're thinking like a developer / coder!  I like it :-)

I do have a debug mode built in.  For the release code, the debug level is set to WARN (only important stuff is printed) but we can set it to INFO or TRACE and then all kinds of trivial stuff is spammed to the console.  If want to experiment, feel free.  

Line 17 of UFO.lua is zebug = Zebug:new()

Change it to zebug = Zebug:new(Zebug.OUTPUT.TRACE)

But it will be overwhelming.

> what if the PostClick event itself not called?
good question!  That code is special protected stuff that can't use my zebug stuff.  I'll go in and add some simple print statements where I can.  The button that's failing, though, is extra-special protected SecureActionButtonTemplate and isn't even Lua code.  It's proprietary, arcane Bliz code that melts my brain.  It doesn't support any of my usual debugging methods.  I'll research what debug methods it provides, if any.

thanks!

**Comment by ScottIngram** [comment] 2024-01-28 06:53
I just checked in a new build that replaces all of the action buttons with macros that simply print the name of button instead of executing the button.  

If you can, please install [9-auto-close-option-breaks-flyout-buttons](https://github.com/ScottIngram/UFO/tree/9-auto-close-option-breaks-flyout-buttons)

**Comment by ScottIngram** [comment] 2024-01-30 17:29
Sorry to keep asking you to do all of this for me, by the way.  I really appreciate your efforts and feedback.  

My problem is that I can't reproduce the error, but I completely believe that it's happening to you.  So, I've thought up a  few experiments to give me more info on how the error might come to be.  I'm trying those now...

**Comment by ScottIngram** [comment] 2024-01-30 18:13
Ok, I think the latest build ([9-auto-close-option-breaks-flyout-buttons](https://github.com/ScottIngram/UFO/tree/9-auto-close-option-breaks-flyout-buttons)) may fix the problem.  Fingers crossed!!!

**Comment by negue** [comment] 2024-02-02 00:55
Sorry for the long response pause

> You're thinking like a developer / coder! I like it :-)
I'm one as well 😬 , just don't know anything about how the addons work / built internally haha

as for the latest build - IT WORKS!!!!!oneoneoneeleven 

splitting that on mouse down and up seems to be the solution 🎉

**Comment by ScottIngram** [comment] 2024-02-02 04:34
Wonderful news!  This is honestly a huge relief.  Thank you so very much for all the help! 

I'll merge the fix into the trunk and push it over to CurseForge soon.

**Closed** 2024-02-02 05:34 UTC
Labels: bug
